sudo: false

language: erlang

otp_release:
 - 19.1
 - 19.2
 - 19.3

install: "true"

before_install:
  - wget https://s3.amazonaws.com/rebar3/rebar3
  - chmod u+x ./rebar3

script:
  - env
  - ./rebar3 plugins list
  - ./rebar3 compile
  - ./rebar3 do xref, ct, coveralls send
